name: quotes_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  flutter_native_splash: ^2.2.3
  fluttertoast: ^8.0.9
  dartz: ^0.10.1
  internet_connection_checker: ^0.0.1+4
  shared_preferences: ^2.0.15
  http: ^0.13.4
  flutter_spinkit: ^5.1.0
  get_it: ^7.2.0
  dio: ^4.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter_native_splash:
  color: "37E2D5"  

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/quote.png
    - assets/images/quoteWord.png
    - lang/ar.json
    - lang/en.json





  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Black.ttf
          weight: 900
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400



